= Vision -Projektthema-
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
0.1, 01.11.2019 
:toc: 
:toc-title: Inhaltsverzeichnis
:sectnums:
// Platzhalter für weitere Dokumenten-Attribute 



== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten des Projekts Paddlec zu sammeln, zu analysieren und zu definieren. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die  Details, wie das Projekt Paddlecs diese Bedarfe erfüllt, werden in der Use-Case und Supplementary Specification beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf das Projekt Paddlec, das von Team 10 entwickelt wird. Das System wird es Rene Budich, M.Sc. erlauben, ein Online-Buchungstool zu nutzen, um damit Reservierungen von Booten zu erleichtern.

=== Definitionen, Akronyme und Abkürzungen
siehe Glossar (Verweis hier einfügen).

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)

== Positionierung
=== Fachliche Motivation
Im Projekt PADELLEC soll eine bedarfsgerechte elektrische Schubunterstützung von Paddelbooten und Kajaks entwickelt werden. Es soll damit das Prinzip des Peddelecs, auf dem Wasser umgesetzt werden. Das Padellec ist ein elektrisches Wasserfahrzeug auf Basis eines klassischen Bootsrumpfs. Dies kann je nach Sportgebiet, Ambitionen oder Präferenzen zum Beispiel ein Kajak oder Kanu sein. 

Im Rahmen dieses Projektes soll ein dezentrales, cloud-basiertes Buchungsportal erarbeitet werden, um eine Vermarktung der Boote zu ermöglichen.
//Erläutern Sie kurz den Hintergrund, in dem das Projekt angesiedelt ist. Welches Problem soll gelöst werden, wie ist es entstanden? Welche Verbesserung wird angestrebt. Achten Sie darauf, eine fachliche (organisatorische, betriebswirtschaftliche) Perspektive einzunehmen.

=== Problem Statement
//Stellen Sie zusammenfassend das Problem dar, das mit diesem Projekt gelöst werden soll. Das folgende Format kann dazu verwendet werden:

|===
|Das Problem |	ist fehlende Vermarktung von Paddlec-Booten
|betrifft |	den Auftraggeber (Rene Budich), die Kunden, evtl. Mitarbeiter
|die Auswirkung davon ist |	keine Buchungen von Paddlec-Booten
|eine erfolgreiche Lösung wäre |	ein Online-Buchungsportal.
|===

////
Beispiel
|===
|Das Problem | aktuelle Informationen zum Stundenplan und Noten einfach zu erhalten
|betrifft |	Studierende der HTW Dresden
|die Auswirkung davon ist |	umständliche und aufwändige Suche nach Noten, Zeiten und Räumen
|eine erfolgreiche Lösung wäre |	die Zusammenführung und benutzer-individuelle Darstellung auf einem mobilen Endgerät
|===
////

=== Positionierung des Produkts 
//Ein Positionierung des Produkts beschreibt das Einsatzziel der Anwendung und die Bedeutung das Projekts an alle beteiligten Mitarbeiter.

//Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:

|===
|Für|	Wassersportinterssierte
|die|	ein elektrisch unterstütztes Boot ausleihen wollen
|Das Produkt ist ein | dezentrales, cloud-basiertes Buchungsportal
|Das	|Verleihstandorte mit jeweiligen Inventarstand anzeigt.
|Im Gegensatz zu	|herkömmlichen Nachfragen über Verleihstandorte
|Unser Produkt|	ermöglicht Online-Buchungen mit aktuellen Informationen über Standort und Inventar der Boote.
|===


//Beispiel Produkt:
//|===
//|Für|	Studierende der HTW
//|die|	die ihren Studienalltag effizienter organisieren möchten
//|Das Produkt ist eine | mobile App für Smartphones
//|Die 	| für den Nutzer Informationen zum Stundenplan und Noten darstellt
//|Im Gegensatz zu	| Stundenplänen der Website und HIS-Noteneinsicht
//|Unser Produkt| zeigt nur die für den Nutzer relevanten Informationen komfortabel auf dem Smartphone an.
//|===

==	Stakeholder Beschreibungen
===	Zusammenfassung der Stakeholder 

[%header]
|===
|Name|	Beschreibung	| Verantwortlichkeiten
|[Benennung des Stakeholder-Typs.]	|[Kurze Beschreibung des Stakeholders.]	|[Fassen Sie die wesentlichen Verantwortlichkeiten des Stakeholder mit Bezug auf das zu entwickelnde System kurz zusammen, d.h. ihr besonderen Interessen. Beispiele: Dieser Stakeholder sorgt dafür, dass das System gewartet wird / dass die angezeigten Daten aktuell sind / überwacht den Projektfortschritt / usw.]
|===

=== Benutzerumgebung
Beschreiben Sie die Arbeitsumgebung des Nutzers. Hier sind einige Anregungen:

//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Anzahl der Personen, die an der Erfüllung der Aufgabe beteiligt sind. Ändert sich das?
. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.

== Produkt-/Lösungsüberblick
=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten und das geplante Release für die Veröffentlichung der Features an.

[%header]
|===
|Bedarf|	Priorität|	Features|	Geplantes Release
|xx|xx|xx|xx
|===
			

== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die nicht von den genannten Features erfasst werden.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen-
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header]
|===
|Anforderung|	Priorität|	Geplantes Release
|xx|xx|xx|
|===
		

